# Generated by Django 3.2.13 on 2022-05-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ial_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
    ]
