# Generated by Django 3.2.13 on 2022-05-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ial_app', '0002_auto_20220522_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='fk_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ial_app.module', verbose_name='Module'),
        ),
    ]
