# Generated by Django 3.2.13 on 2022-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial_app', '0003_alter_topic_fk_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='extra',
            field=models.BooleanField(default=False, verbose_name='Extra module topic'),
        ),
    ]
