# Generated by Django 3.2.13 on 2022-07-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ial_app', '0004_alter_topic_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exerciselist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
    ]
