# Generated by Django 3.2.13 on 2022-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial_app', '0005_auto_20220704_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciselist',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
    ]
